gui:
  theme:
    activeBorderColor:
      - "#bf15a0"

    selectedLineBgColor:
      - "#5f004b"
  spinner:
    frames:
      - "＿(ᵔ⩊ ᵔ)／"
      - "＼(ᵔ⩊ ᵔ)＿"
    rate: 3
  expandFocusedSidePanel: true
  showPanelJumps: false
  mouseEvents: false
  nerdFontsVersion: "3"
  showRootItemInFileTree: false

git:
  disableForcePushing: true
  log:
    showWholeGraph: true
  parseEmoji: true
  branchLogCmd: git l --color=always
